[package]
name = "epoll"
version = "0.4.1"
authors = ["Nathan Sizemore <nathanrsizemore@gmail.com>"]
description = "Epoll interface"
readme = "README.md"
keywords = ["epoll"]
license = "MPL-2.0"
repository = "https://github.com/nathansizemore/epoll"
documentation = "http://nathansizemore.github.io/epoll/epoll/index.html"

[dependencies]
libc = "^0.2"
simple-slab = "^0.2"
bitflags = "^0.7"
