[package]
name = "epoll"
version = "0.3.1"
authors = ["Nathan Sizemore <nathanrsizemore@gmail.com>"]
description = "Linux epoll wrapper"
repository = "https://github.com/nathansizemore/epoll"
readme = "README.md"
keywords = ["epoll"]
license = "MPL 2.0"


[dependencies]
errno = "*"
libc = "*"
